[mypy]
python_version = 3.12
strict = false
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true

[mypy-celery.*]
ignore_missing_imports = true

[mypy-motor.*]
ignore_missing_imports = true

[mypy-redbeat.*]
ignore_missing_imports = true

[mypy-passlib.*]
ignore_missing_imports = true
